# Generated by Django 4.0.6 on 2022-07-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renta_autos', '0003_cliente_changed_by_historicalcliente_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='HistoricalCliente',
        ),
    ]
