# Generated by Django 4.0.6 on 2022-07-29 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mirage.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renta_autos', '0005_auditoriahistory_cliente_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('fec_alta', models.DateTimeField(blank=True, editable=False)),
                ('user_name', models.CharField(max_length=150)),
                ('codigo_zip', models.CharField(max_length=50)),
                ('credit_card_num', mirage.fields.EncryptedCharField(max_length=255)),
                ('credit_card_ccv', mirage.fields.EncryptedCharField(max_length=255)),
                ('cuenta_numero', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('geo_latitud', models.FloatField()),
                ('geo_longitud', models.FloatField()),
                ('color_favorito', models.CharField(max_length=100)),
                ('foto_dni', models.TextField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(max_length=15)),
                ('avatar', models.TextField(blank=True, max_length=100, null=True)),
                ('fec_birthday', models.DateField()),
                ('compras_realizadas', models.IntegerField(blank=True, default=0, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='history',
        ),
        migrations.AddField(
            model_name='cliente',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuditoriaHistory',
        ),
    ]
